name: GTmetrix Performance Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  gtmetrix-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run GTmetrix Test
        env:
          GTMETRIX_API_KEY: ${{ secrets.GTMETRIX_API_KEY }}
        run: |
          curl -X POST https://gtmetrix.com/api/2.0/tests \
          -H "Authorization: Basic $(echo -n ${GTMETRIX_API_KEY}: | base64)" \
          -H "Content-Type: application/vnd.api+json" \
          -d '{"data": {"type": "test", "attributes": {"url": "https://www.google.com/"}}}' \
          -o gtmetrix-response.json



      - name: Display Results
        run: |
          # Extract and display the results
          cat gtmetrix-response.json
          echo "GTmetrix Test Completed! Review the response above for results."
