name: GTmetrix Performance Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  gtmetrix-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run GTmetrix Test
        env:
          GTMETRIX_API_KEY: ${{ secrets.GTMETRIX_API_KEY }}
        run: |
          # Send a POST request to start a GTmetrix test
          curl -X POST https://gtmetrix.com/api/2.0/tests \
            -H "Authorization: Basic $(echo -n ${GTMETRIX_API_KEY}: | base64)" \
            -H "Content-Type: application/vnd.api+json" \
            -d '{"data": {"type": "test", "attributes": {"url": "https://www.google.com/"}}}' \
            -o gtmetrix-response.json
          
          # Display the raw GTmetrix response
          echo "Raw GTmetrix Response:"
          cat gtmetrix-response.json
          
          # Extract the report PDF URL
          export REPORT_URL=$(jq -r '.data.attributes.report_pdf' gtmetrix-response.json)
          echo "Extracted Report URL: $REPORT_URL"
          
          # Ensure the report URL is valid
          if [ -z "$REPORT_URL" ] || [ "$REPORT_URL" == "null" ]; then
            echo "Failed to retrieve the GTmetrix report URL"
            exit 1
          fi

      - name: Display Results
        env:
          N8N_WEBHOOK_URL: ${{ secrets.N8N_WEBHOOK_URL }}
        run: |
          # Post the report URL to n8n webhook
          curl -X POST $N8N_WEBHOOK_URL \
            -H "Content-Type: application/json" \
            -d '{"report_url": "'"$REPORT_URL"'"}'
          
          echo "GTmetrix Test Completed! The full response and report URL are displayed above."
