name: GTmetrix Performance Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  gtmetrix-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run GTmetrix Test
        env:
          GTMETRIX_API_KEY: ${{ secrets.GTMETRIX_API_KEY }}
        run: |
          # Trigger GTmetrix Test
          curl -X POST https://gtmetrix.com/api/2.0/tests \
            -H "Authorization: Basic $(echo -n ${GTMETRIX_API_KEY}: | base64)" \
            -H "Content-Type: application/vnd.api+json" \
            -d '{"data": {"type": "test", "attributes": {"url": "https://www.google.com/"}}}' \
            -o gtmetrix-response.json

          SELF_LINK=$(jq -r '.links.self' gtmetrix-response.json)
          if [ -z "$SELF_LINK" ] || [ "$SELF_LINK" == "null" ]; then
            echo "Failed to retrieve the self link for the GTmetrix test"
            exit 1
          fi

          # Poll for Test Completion
          MAX_RETRIES=10
          RETRY_DELAY=30
          for i in $(seq 1 $MAX_RETRIES); do
            curl -X GET "$SELF_LINK" \
              -H "Authorization: Basic $(echo -n ${GTMETRIX_API_KEY}: | base64)" \
              -o gtmetrix-detailed-response.json

            STATE=$(jq -r '.data.attributes.state' gtmetrix-detailed-response.json)
            if [ "$STATE" == "completed" ]; then
              break
            elif [ "$i" -eq "$MAX_RETRIES" ]; then
              echo "GTmetrix test did not complete within the timeout period."
              exit 1
            fi
            sleep $RETRY_DELAY
          done

          # Fetch Report PDF Link
          REPORT_PDF=$(jq -r '.data.links.report_pdf // empty' gtmetrix-detailed-response.json)
          
          # Handle different error cases
          if [ -z "$REPORT_PDF" ]; then
            if jq -e '.data.links.report_pdf' gtmetrix-detailed-response.json > /dev/null; then
              echo "The GTmetrix report PDF link is explicitly 'null'."
            else
              echo "The GTmetrix report PDF link is missing from the response."
            fi
            exit 1
          fi
          
          # Save the PDF link to GITHUB_ENV
          echo "REPORT_PDF=$REPORT_PDF" >> $GITHUB_ENV


      - name: Send Report Link to n8n
        env:
          N8N_WEBHOOK_URL: ${{ secrets.N8N_WEBHOOK_URL }}
        run: |
          echo "Sending the following data to n8n: {\"report_pdf\": \"$REPORT_PDF\"}"

          # Send the report PDF link to n8n webhook
          curl -X POST "$N8N_WEBHOOK_URL" \
            -H "Content-Type: application/json" \
            -d "{\"report_pdf\": \"$REPORT_PDF\"}"

          echo "GTmetrix Report PDF Link sent to n8n!"
